### ISSUE TITLE
Blaze (pay-as-you-go) plan

### ISSUE THREAD

**Issue by wapiters** [Domi2803/HeartWear#3]
Hi, when I try to do firebase deploy. I get a message that this can not be done with the free plan. Did I do something wrong or does this mean I have to activate the Blaze plan to be able to use this app?

!  functions: package.json indicates an outdated version of firebase-functions.
Please upgrade using npm install --save firebase-functions@latest in your functions directory.

=== Deploying to 'projectName'...

i  deploying database, functions
i  database: checking rules syntax...
+  database: rules syntax for database projectName-default-rtdb is valid
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
!  functions: missing required API cloudbuild.googleapis.com. Enabling now...
+  functions: required API cloudfunctions.googleapis.com is enabled

Error: Your project projectName must be on the Blaze (pay-as-you-go) plan to complete this command. Required API cloudbuild.googleapis.com can't be enabled until the upgrade is complete. To upgrade, visit the following URL:

https://console.firebase.google.com/project/projectName/usage/details

**Comment by Domi2803** [comment]
Hey, could you try to deploy with

`firebase deploy --only hosting,database`

as per recent Firebase changes, Cloud Functions are no longer included in the free plan, but shouldn't be necessary for WearOS, only for Tizen (Galaxy Watch) smartwatches.

**Comment by wapiters** [comment]
That worked, but i have offcourze a galaxy watch, so in the end i still need to change my plan. If you are able to add stress measurement to your app I will buy the apps from the galaxy store en change the firebase plan with pleasure.

**Comment by wapiters** [comment]
May be its a good idea to also add this to the readme file.

Type keytool -alias "AndroidDebugKey" -genkeypair in the terminal of your android studio give it a password of android. Otherwise the 'signingReport' will not work.
The rest of the fields or questions asked after that don't matter so just press Enter.
Go to your home directory (C:\Users<YOUR USERNAME>) and look for a file named as .keystore.
Rename .keystore to debug.keystore.
Now copy and paste it to (C:\Users<YOUR USERNAME>.android).
Re-run the signReport task to generate a new key for APP.

**Comment by Domi2803** [comment]
Thank you very much, I didn't think about having to create a keystore before the signing report, I will add that to the readme.

Also note, right now you can just compile the Tizen app without deploying any backend, it'll work with the official backend at heartwear.web.app, since I needed to create an API from scratch. Selfhosting is only required for WearOS, as the alternative was to include my credentials in the source code, which was not something I wanted to do. 

As for the stress measurement, I'll definitely consider it, though I can't guarantee if and when it'll be implemented. 
But thanks for your contributions!
